trigger: none

pool: TCC-PUC Agent Pool

variables:
- name: dotnet_project
  value: ModuloInformacoesCadastrais/ModuloInformacoesCadastrais.API/ModuloInformacoesCadastrais.API.csproj

steps:
  - task: UseDotNet@2
    displayName: Instalando .NET 6 no agent
    inputs:
      version: 6.x
      packageType: sdk
  - task: DotNetCoreCLI@2
    displayName: Fazendo o restore das dependências do projeto
    inputs:
      command: restore
      projects: $(Build.SourcesDirectory)/$(dotnet_project)
  - task: DotNetCoreCLI@2
    displayName: Realizando o build do projeto
    inputs:
      command: build
      projects: $(Build.SourcesDirectory)/$(dotnet_project)
      arguments: -c Release
      publishWebProjects: false
