pool: TCC-PUC Agent Pool

variables:
- name: dotnet_project
  value: ModuloInformacoesCadastrais.API/ModuloInformacoesCadastrais.API.csproj

steps:
  - task: UseDotNet@2
    enabled: false
    displayName: Install .NET 6 on agent
    inputs:
      version: 6.x
      packageType: sdk
  - task: DotNetCoreCLI@2
    displayName: .NET restore
    inputs:
      command: restore
      projects: $(dotnet_project)
  - task: DotNetCoreCLI@2
    displayName: .NET build
    inputs:
      command: build
      projects: $(dotnet_project)
      arguments: -c Release
      publishWebProjects: false
  - task: DotNetCoreCLI@2
    displayName: .NET test
    inputs:
      command: test
      projects: $(dotnet_project)
      arguments: >-
        /p:CollectCoverage=true
        /p:CoverletOutputFormat=opencover
        --collect "Code coverage"
        --logger:trx
